### ISSUE TITLE
Reconcile loop causes a lot of "no-op" updates

### ISSUE THREAD

**Issue by mhutter** [vshn/espejo#117]
## Describe the bug

Code in question:

https://github.com/vshn/espejo/blob/v0.4.0/controllers/syncconfig_controller.go#L125-L145

When there are no actual changes between the desired state and existing resources, the reconciliation loop will still cause the existing objects to be updated with the new `resourceVersion`. This causes an `Update` event for all watchers.

For example, on one OCP cluster espejo manages 350 NetworkPolicies. The reconciliation loop causes 350 update events a couple of times every minute.

## Additional context

I suspect this is what triggered https://bugzilla.redhat.com/show_bug.cgi?id=2091238

## Expected behavior

No updates if the existing resource already matches the desired state.

## To Reproduce

See any of our existing OCP4 clusters

**Comment by anothertobi** [comment]
The NetworkPolicies we sync with espejo contain a change compared to the actual resource in the cluster:
```
      spec:
         egress: []
```

The Kubernetes API defaults to `omitempty` with the empty array and this always results in a no-op update. I don't think this is something we have to handle in espejo (iirc, ArgoCD doesn't handle this and shows diffs like this as unsynced).

I think this is actually a bug in https://github.com/projectsyn/component-networkpolicy or our configuration of it. If we removed the empty egress array from the NetworkPolicies, espejo would still continue to revert changes to `.spec.egress`.
