### ISSUE TITLE
Allow Regex in Name Matches

### ISSUE THREAD

**Issue by srueg** [vshn/espejo#28]
Allow to use Regex expressions in the `namespaceSelector.matchNames` and `namespaceSelector.ignoreNames` (implemented in #27) fields.

This can be helpful to select multiple namespaces which don't have a common label, but a common naming scheme. For example: `namespaceSelector.ignoreNames: ^openshift-.*$`

**Comment by ccremer** [comment]
How would we differentiate between normal names and Regexes? Should we enclose regex in `/`, e.g. `/^openshift-.*$/` so it's clear that this property should be treated as regex? Or should we assume it to be regex by default and maybe the name property `ignoreNamesRegex` to make it clear?

**Comment by ccremer** [comment]
Thinking about this: If we were to put multiple patterns into this, one would have to solve this with regex e.g. `(default)|(opensfhit-.*)`. Maybe it makes more sense to have an array of regex patterns instead (like the `matchNames` property)

**Comment by srueg** [comment]
Couldn't we just treat every string as regex? If there's no special control characters, it will just do a full match, as expected.
