### ISSUE TITLE
Allow syncing of HorizontalPodAutoscaler objects

### ISSUE THREAD

**Issue by thom8** [vshn/espejo#9]
We're looking for a solution that can potentially sync HorizontalPodAutoscaler objects across a cluster based on namespace labels.

This is so we can have some default scaling rules applied to projects and allow updating the object from a centralised configuration object.

Would you consider allowing the syncing of HorizontalPodAutoscaler objects?

**Comment by srueg** [comment]
I guess the better approach would be to change the ClusterRole (or create a new one) for specific deployments. This [ClusterRole](https://github.com/vshn/espejo/blob/master/deploy/clusterrole.yaml) is only meant to be an example to demo a possible use case.

**Comment by thom8** [comment]
Thank @srueg, will look at adding a separate `ClusterRole` and `ClusterRoleBinding` for this.

Closing #10
